-- FUNCIÓN PARA OBTENER NOMBRE DEL VENDEDOR
CREATE OR REPLACE FUNCTION FN_NOMBRE_VENDEDOR(P_COD_VEN NUMBER) RETURN VARCHAR2 
IS
    V_NOMBRE_VEN_MAYUS      VENDEDORES.NOM_VEN%TYPE;
BEGIN 
    -- OBTENER NOMBRE DEL VENDEDOR EN FORMATO MAYÚSCULA
    SELECT UPPER(NOM_VEN)
    INTO V_NOMBRE_VEN_MAYUS
    FROM VENDEDORES
    WHERE COD_VEN = P_COD_VEN;
    
    RETURN V_NOMBRE_VEN_MAYUS;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 'SIN NOMBRE';
END FN_NOMBRE_VENDEDOR;
/
